apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: client
          image: client:0.1
          command: ['echo', 'Hello there']
      restartPolicy: Never
